In [1]:
import pandas as pd
var = pd.read_csv("Beast.csv")
var

,No.,Symbol,Security,Today - Volume,Avg. Volume,Change
0,1,ELECTHERM,Electrotherm (India) Limited,473907,9547,50.110003
1,2,NBIFIN,N. B. I Industrial Finance Company,5754,154,37.202586
2,3,HINDCON,Hindcon chemicals Limited,304759,9248,32.953450
3,4,GKWLIMITED,GKW Limited,21375,711,30.049203
4,5,21STCENMGM,21st century Management Services,110375,3879,31.049203
5,6,ALPHAGEO,Alphageo (india) Limited,1,8356,27.852613
6,7,UNIENTER,Uniphos Enterprises Limited,1,8357,21.528002
7,8,JAGSNPHARM,Jagsonpal Pharmaceuticals Limited,1,73134,17.801420
8,9,SKMEGGPROD,SKM Egg Products Export (India),1,87775,18.801420
9,10,SWELECTES,Swelect Energy Systems Limited,1,87776,16.938733
10,11,NAHARPOLY,Nahar Poly Films Limited,1,38574,15.555297
11,12,PODDARHOUS,Poddar Housing and Development,1,3012,15.283833
12,13,LINC,Linc Limited,60551,4076,14.853673
13,14,LINC123,Liinc Limited123,60550,4075,15.856735